---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: omni

suites:
  - name: default
    run_list:

      - recipe[oracle-omni]

    attributes:
      oracle-omni:
        oracle:
          files_url: http://3.62.72.4
        rdbms:
          storage_type: ASM
        grid:
          device_prefix: sd
          ocr_disk: /dev/sdb
          data_disk: /dev/sdc
          log_disk: /dev/sdd
