---
driver:
  name: vagrant
  customize:
    memory: 3072

provisioner:
  name: chef_zero

platforms:
  - name: omni

suites:
  - name: default
    run_list:

      - recipe[oracle-omni::prephost]
      - recipe[oracle-omni::installgi]
      - recipe[oracle-omni::installrdbms]
      - recipe[oracle-omni::configureasm]
      - recipe[oracle-omni::createdbdgs]
      - recipe[oracle-omni::createdb]

    attributes:
      oracle-omni:
        oracle:
          home_mount: /u01
          files_url: http://192.168.1.114:8887
        rdbms:
          version: 12.1.0.2
          storage_type: ASM
        grid:
          device_prefix: sd
          ocr_disk: /dev/sdc
          data_disk: /dev/sdd
          log_disk: /dev/sde
